# Generated by Django 4.1.2 on 2022-10-17 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbrev', models.CharField(max_length=50)),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('dept', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prep', models.CharField(max_length=100)),
                ('note1', models.CharField(max_length=100)),
                ('note2', models.CharField(max_length=100)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_code', models.CharField(max_length=20, verbose_name='Course Code')),
                ('name', models.CharField(max_length=50, verbose_name='Course Name')),
                ('credits', models.CharField(max_length=50, verbose_name='Credits')),
                ('contact_hours', models.CharField(max_length=50, verbose_name='Contact Hours')),
                ('textbook', models.CharField(max_length=100, verbose_name='Textbooks')),
                ('course_description', models.TextField()),
                ('prereq', models.CharField(max_length=100, verbose_name='Prerequisites')),
                ('co_req', models.CharField(max_length=100, verbose_name='Co-requisites')),
                ('course_classification', models.CharField(max_length=50, verbose_name='Course Classification')),
                ('course_objective', models.TextField()),
                ('ILO', models.TextField()),
                ('s_outcomes', models.TextField()),
                ('prelim', models.TextField()),
                ('midterm', models.TextField()),
                ('finals', models.TextField()),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='syllabus.instructor')),
            ],
        ),
    ]
