# Generated by Django 4.1.2 on 2022-10-17 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0002_course_approval_remove_course_instructor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='approval',
            new_name='signatories',
        ),
        migrations.AlterField(
            model_name='course',
            name='instructor',
            field=models.ManyToManyField(blank=True, to='syllabus.instructor'),
        ),
    ]
