# Generated by Django 4.1.2 on 2022-10-19 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0003_rename_approval_course_signatories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='credits',
            field=models.IntegerField(verbose_name='Credit Units'),
        ),
    ]
