# Generated by Django 4.1.2 on 2022-10-19 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0004_alter_course_credits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='contact_hours',
            field=models.PositiveIntegerField(verbose_name='Contact Hours'),
        ),
        migrations.AlterField(
            model_name='course',
            name='credits',
            field=models.PositiveIntegerField(verbose_name='Credit Units'),
        ),
    ]
