# Generated by Django 4.1.2 on 2022-11-02 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0005_alter_course_contact_hours_alter_course_credits'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='textbook2',
            field=models.CharField(max_length=100, null=True, verbose_name='Other Supplemental Materials'),
        ),
    ]
