# Generated by Django 4.1.3 on 2022-12-05 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0006_course_textbook2'),
    ]

    operations = [
        migrations.CreateModel(
            name='course_period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(max_length=300, verbose_name='Module')),
            ],
        ),
        migrations.AlterField(
            model_name='course',
            name='finals',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finals', to='syllabus.course_period'),
        ),
        migrations.AlterField(
            model_name='course',
            name='midterm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='midterm', to='syllabus.course_period'),
        ),
        migrations.AlterField(
            model_name='course',
            name='prelim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prelim', to='syllabus.course_period'),
        ),
    ]
