# Generated by Django 4.1.2 on 2022-12-05 13:50

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0008_alter_course_ilo_alter_course_finals_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='ILO',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='finals',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='midterm',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='prelim',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='s_outcomes',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
